project:
  type: website

website:
  title: "CFP Eliminator"
  google-analytics: "G-SWLL1S2Y3F"   # <— replace with your real ID
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Weekly Analysis
        href: analysis.qmd
      - text: Bracket
        href: bracket.qmd
      - text: Poll
        href: poll.qmd
      - text: Articles
        href: articles.qmd
      - text: About
        href: about.qmd
  search: true
  page-footer:
    left: "© 2025 Illumined Analytics"
    right: |
      <a href="mailto:stephen@illumined.io">Contact</a> · 
      <a href="/privacy.html">Privacy</a>

format:
  html:
    theme:
      - cosmo
      - assets/custom.scss
    page-layout: article
    smooth-scroll: true
    toc: false
